# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-09 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0004_auto_20161008_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='posttags', to='photoapp.Tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='phototags', to='photoapp.Tag'),
        ),
    ]
