# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-09 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0005_auto_20161009_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='photo',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
